# Generated by Django 4.1.3 on 2023-01-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('id',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
